name: datastore-bukkit
version: ${git.commit.id.abbrev}
main: com.solexgames.datastore.bukkit.DataStoreBukkit

author: SolexGames
website: https://solexgames.com

depend: [commonlibs-bukkit, Scandium]
